package uno.cards;

//  This file provides a set of classes that may be used
//  to implement an UNO Deck.  
//
//  Initial code framework generated by StarUML(tm) Java Add-In
//
//  @ Project : UNO_Model
//  @ File Name : UNO_Card.java
//  @ Date : 4/1/2015
//  @ Author : S. Sigman
//
//

/** 
 * The UNO_Card class provides the base class for all UNO cards.  Both face card and action card
 * classes are derived from this class.  
 */
public class UNO_Card implements Comparable<UNO_Card>
{
	/** 
	 * Card Color: Blue
	 */
	public static int BLUE = 0;
	
	/** 
	 * Card Color: Red
	 */
	public static int RED = 1;
	
	/** 
	 * Card Color: Green
	 */
	public static int GREEN = 2;
	
	/**
	 * Card Color: Yellow
	 */
	public static int YELLOW = 3;
	
	/** 
	 * Card Color: Black (Wild Cards)
	 */
	public static int BLACK = 4;
	
	private int color;  // Color of the card
	
	/** *
	 * Constructor for an UNO_Card of the specified color.  This constructor 
	 * constructs a base card.  Cards for game play should be constructed 
	 * using one of the classes Face_Card or Action_Card
	 *
	 * @param clr The color of the card.
	 */
	public UNO_Card(int clr)
	{
	   color = clr;
	}
	
	/** 
	 * This method returns the color of the card.  Possible colors are UNO_Card.BLUE,
	 * UNO_Card.RED, UNO_Card.GREEN, UNO_Card.YELLOW, and UNO_Card.BLACK.
	 * 
	 * @return The color of the card.
	 */
	public int getColor()
	{
	   return color;
	}
	
	/** 
	 * This method allows two cards to be compared.  The cards are equal if they
	 * are the same color. Otherwise, they are unequal.
	 * 
	 * @param other The UNO card to compare with this card.
	 * @return 0 if the cards are the same color; otherwise, 1.
	 */
	public int compareTo(UNO_Card other)
	{
	   if (this.getColor() == other.getColor())
	      return 0;
	   else
	      return 1;
	}
	
	/**
	 * This method returns a string describing the card.
	 * 
	 * @return String describing the card.
	 */
	public String toString()
	{  
	    return "Basic UNO Card - color: " + getColorAsString();
	}
	
	/**
	 * getColorAsString returns the color of the card as a
	 * string object.
	 * 
	 * @return The color of the card as a String.
	 */
	protected String getColorAsString()
	{
	    // Determine the correct color string to return
	    String cardColor = "";
	    if (color == BLUE)
	       cardColor = "BLUE";
	    else if (color == RED)
	       cardColor = "RED";
	    else if (color == YELLOW)
	       cardColor = "YELLOW";
	    else if (color == GREEN)
	       cardColor = "GREEN";
	    else
	       cardColor = "BLACK";	      
	    return cardColor;
	}
}
